server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        regex: '/(.*)'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: logstream
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: application
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project
      - source_labels: ['__meta_docker_container_log_path']
        target_label: __path__
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: logLevel
            logger: loggerName
            thread: threadName
            message: message
            service: mdc.service
            path: mdc.path
      - labels:
          level:
          logger:
          service:
      - output:
          source: message
